### ISSUE TITLE
afbeeldingen aanleveren voor introteksten

### ISSUE THREAD

**Issue by ndkv** [ndkv/expeditiewikipedia#102]

**Comment by Ftmeijer** [comment]
In de google excel sheet zit een tab overzicht expedite. Daar vind je of een naam van een afbeelding (in de net gedeelde dropbox, of een link naar commons. Ik vul die lijst vrijdag verder aan.

**Comment by ndkv** [comment]
Ik heb de afbeeldingen uit sheet in app verwerkt.
