### ISSUE TITLE
Historische Kaart standaard aan of uit

### ISSUE THREAD

**Issue by memunnik** [ndkv/expeditiewikipedia#110]

**Comment by memunnik** [comment]
Bij het kiezen van een expeditie vind ik het direct aanwezig zijn /aanstaan van historische kaarten rommelig er uit zien.  Wat mij betreft alleen aanzetten indien daar gebruiker actief voor kiest!

**Comment by ndkv** [comment]
Ik heb kaart nu uitgezet in overzichtsscherm. Willen we daar uberhaupt kaarten hebben? Zo niet dan schakel ik knop uit.

**Comment by Ftmeijer** [comment]
Van mij hoeft het niet.

-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Bart stelt voor om hist. kaart ook uit te zetten in expeditie scherm en gebruikers deze handmatig te laten aanzetten. Wat vinden jullie?

**Comment by memunnik** [comment]
Mee eens!
