### ISSUE TITLE
tweetaligheid introductie popup

### ISSUE THREAD

**Issue by ndkv** [ndkv/expeditiewikipedia#116]

**Comment by ndkv** [comment]
Ideeen waar ik taalswitch control kan plaatsen? 

Een mogelijkheid is om Welkom! / Welcome! neer te zetten en deze aanklikbaar te maken. Klikken op Welkom! toont NLse text en vice versa.

**Comment by Ftmeijer** [comment]
Goed idee

Kan je dan de actieve kop Vet maken en de niet actieve een lichte kleur geven oid?


-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>
