### ISSUE TITLE
Tekst in 'Lees meer' scherm moet veel korter

### ISSUE THREAD

**Issue by ndkv** [ndkv/expeditiewikipedia#72]
Nog liever een blok links met tekst, eindigend met de lees meer knop. En dan rechts altijd een plaatje, eventueel rechtstreeks uit het wikipedia artikel zelf.

**Comment by ndkv** [comment]
Tekst mag niet langer zijn dan beschikbare ruimte, niet scrollen.

**Comment by ndkv** [comment]
@ftmeijer OK als tekst uit Wikipedia hoofdlemma komt (afgekapt op 150-200 woorden)?

**Comment by Ftmeijer** [comment]
Ja prima.
 Is dat van een plaatje (mits in wikipedia artikel aanwezig) mogelijk?

**Comment by Ftmeijer** [comment]
Aanvullend: is het niet mogelijk om bij artikelen alleen links tekst te plaatsen (100-150 worden) en rechts, indien aanwezig een afbeelding uit commons. Wij kunnen in de excel aangeven welke afbeelding dat wordt. Dat maakt het mogelijk om bij de boeken zowel de illustraties als het wikipedia artikel over het boek in 1 poi op te nemen.

**Comment by ndkv** [comment]
Dat kan als jullie inderdaad URL van afbeelding in contentlijst opnemen.

Samenvattend: 

-  expeditie introductieteksten: **links** een korte redactionele tekst met **rechts** een afbeelding uit Commons [1]. 

- PoI teksten: **links** een korte tekst (~150-200 woorden)  uit Wikipedia API, **rechts** een afbeelding uit Commons **OF** aangedragen door redactie.

[1] Belangrijk: komen alle afbeeldingen voor introteksten uit Commons?

Redactionele teskten/afbeeldingen worden in contentlijst opgenomen, overige teksten en afbeeldingen komen uit Wikipedia/Commons APIs.

@ftmeijer Klopt dit?

**Comment by Ftmeijer** [comment]
Een aanpassing: 

expeditie introductieteksten: grote afbeelding over hele breedte (liggend) met daar boven een titel korte introductietekst aangeleverd door de redactie. 

NB: ik weet niet of dit voor VM expeditie voldoende is. Er is in het ontwerp ook een variant met een uitgeklapte intro met meer woorden. 

Al het beeld, voor zowel de POi als expeditie intro’s komen of uit Commons, of apart aangeverd. In alle gevallen worden ze opgenomen in de contentlijst. 

Wij zullen voor alle artikelen een afbeelding-link opnemen in de kolom afbeelding.

**Comment by Ftmeijer** [comment]
Nog een ding voor de wish list. 
In de rechterkolom in plaats van 1 afbeelding uit commons een dia show van een serie afbeeldingen met dezelfde categorie. Bijvoorbeeld: https://commons.wikimedia.org/wiki/Category:North_New_Guinea_Expedition

**Comment by ndkv** [comment]
Vraag over "titel korte introductietekst" Hoe kort is kort? Als tekst te kort is komt er veel lege ruimte vrij...

Kunnen jullie "grote afbeeldingen over hele breedte" zo snel mogelijk aanleveren zodat ik kan beginnen met implementatie. Ik verwacht dat er de nodie haken en ogen aan zitten bijv. wat gebeurt er als plaatje hoger/breder is dan de beschikbare ruimte en andersom... 

RE: uitgeklapte intro - Het bouwen van een nieuwe interface control kost veel tijd, ik probeer zoveel mogelijk controls voor beide expedities te gebruiken.

**Comment by ndkv** [comment]
@ftmeijer Ik heb weergave van introteksten en PoI teksten aangepast volgens grafisch ontwerp en bovenstaande. 

Er blijft weinig ruimte over voor de grote afbeelding over de breedte. We moeten een keus maken; huidig ontwerp of alleen grote afbeelding over de breedte. Beide (zoals in grafisch ontwerp) wordt lastig omdat een van de twee afbeelding te klein wordt. Indien we voor grote afbeelding kiezen is het de vraag hoe titel en beschrijving op te nemen. 
Titel kan ik zwarte balk bovenaan. Beschrijving wordt dan een regel boven de grote afbeelding. 

Wat zullen we doen? 

Persoonlijk vind ik de huidige opzet OK omdat je meer tekst kan laten zien.

**Comment by ndkv** [comment]
Graag in issue #69 verder praten over grote afbeelding.

**Comment by ndkv** [comment]
Tekst komt nu uit Wiki API en is ~500 woorden.  Aan opmaak wordt gesleuteld.

**Comment by Ftmeijer** [comment]
In mijn poi scherm zijn het nu slechts 60 woorden. 


-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Right, ik bedoel 500 tekens.

**Comment by Ftmeijer** [comment]
Ah,

Dat mag dan van mij wel wat meer worden, zodat het een beetje opvult. Zodat de wikipedia knop ongeveer gelijk komt aan de afbeelding. Of wordt dat lelijk?

Verder vind ik de witruimte onder de afbelding wel erg breed. Het kruisje is nu heel groot geworden. Kan het kruis niet over de afbeelding heen zoals bij het expeditie introscherm?



-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Alles kan. :)

Ik ga experimenteren en stuur een paar screenshots.

**Comment by ndkv** [comment]
Experiment 1

![vmontwerp4](https://cloud.githubusercontent.com/assets/778666/6740096/b3f11f72-ce7d-11e4-9212-8a9bc99e49b9.PNG)

In nabootsing van iPad portrait mode heb ik scherm vrij nauw gemaakt. Je merkt gelijk dat niet elke foto zich leent voor deze aanpak. In landscape is schip net te zien. 

Lees meer knop trekt iets te veel aandacht... 

... wat  ook kan is deze vervangen door een link met tekst.
