### ISSUE TITLE
zoomknoppen staan niet op een lijn

### ISSUE THREAD

**Issue by ndkv** [ndkv/expeditiewikipedia#77]

**Comment by Ftmeijer** [comment]
Net getest op ipad mini. 
Ik heb het niet kunnen reproduceren. Knopjes blijven netjes naast elkaar staan, zowel in landcape als portrait. 

---

Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl mailto:f.t.meijer@academischerfgoed.nl 
06-11060137

www.academischerfgoed.nl http://www.academischerfgoed.nl/ 
www.academischecollecties.nl http://www.academischecollecties.nl/
