### ISSUE TITLE
positie binnen de app is niet duidelijk

### ISSUE THREAD

**Issue by ndkv** [ndkv/expeditiewikipedia#81]
Het toevoegen van een duidelijke titel zou een hoop schelen. Ook onduidelijk of je je in expeditieoverzicht of binnen een expeditie bevindt.

**Comment by ndkv** [comment]
Lijkt op https://waffle.io/ndkv/vm/cards/54fdf4cf9a47a20300fdf509

**Comment by ndkv** [comment]
Ik heb de titel van expeditie in zwartebalk boven kaart geplaatst. Helpt dit om je te orienteren?

**Comment by Ftmeijer** [comment]
Ja prima!

-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>
