### ISSUE TITLE
Het is moelijk om naar expeditieoverzicht te navigeren

### ISSUE THREAD

**Issue by ndkv** [ndkv/expeditiewikipedia#82]

**Comment by ndkv** [comment]
Overzicht van expedities is niet in grafisch ontwerp opgenomen. Ideeen hoe dit op te lossen zijn welkom.

**Comment by ndkv** [comment]
Lijkt op feedback Tremani, zie https://waffle.io/ndkv/vm/cards/54fdf49cb0ea75030064ecbe

**Comment by ndkv** [comment]
Ik overweeg om een 'Home' / 'Naar exepedities' link naast logo te plaatsen. Any thoughts?

**Comment by Ftmeijer** [comment]
Goed idee:


Een tekst / link zelfde font als Titel expeditie

Alle expedities  / Expeditions

Eentueel met pijl terug <— 



-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>
