### ISSUE TITLE
knop 'lees meer wikipedia' aan de zijkant staat op een rare plek

### ISSUE THREAD

**Issue by ndkv** [ndkv/expeditiewikipedia#89]
suggestie: plaats het naast de twee knoppen 'terug en start expeditie' onder de artikelen

**Comment by Ftmeijer** [comment]
Dat lijkt me niet zo'n goed idee. Het zijn verschillende soorten acties. 

Dat de knop op een rare plek staat klopt wel. Ik zou hem in het tekstveld, rechts onderaan de afgebroken tekst zetten. 
Maar dat is iets dat we even moeten zien, denk ik.

**Comment by ndkv** [comment]
Goed.

Ik pak dit als eerste op.

**Comment by ndkv** [comment]
Knop staat nu onderaan PoI Wikipedia tekst.

**Comment by ndkv** [comment]
Nu botst het met 'Terug' / 'Back' knop. Beste oplossing is om deze te veranderen in een kruisje en rechts onder foto te plaatsen.

**Comment by ndkv** [comment]
Nu komt knop onderaan PoI tekst te staan.

**Comment by NieuweMeestersDelft** [comment]
Is hier nu een besluit over genomen?

**Comment by ndkv** [comment]
We hebben inteface opnieuw vormgegeven, zie 
https://github.com/ndkv/vm/issues/72

**Comment by ndkv** [comment]
'Lees meer' icoon vervangen door tekst + icoontje dat je uit applicatie stapt

**Comment by ndkv** [comment]
Done. 

Moeten nog even kijken waar link precies moet komen te staan.

**Comment by ndkv** [comment]
@Ftmeijer Is de link goed zo of zal ik het achter/onder puntjes van tekst plaatsen?

![wikipedia lees meer](https://cloud.githubusercontent.com/assets/778666/7628639/14724816-fa26-11e4-885a-11cb3e336267.PNG)

**Comment by Ftmeijer** [comment]
Ik denk dat achter de puntjes de beste plek is.

---

Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl mailto:f.t.meijer@academischerfgoed.nl 
06-11060137

www.academischerfgoed.nl http://www.academischerfgoed.nl/ 
www.academischecollecties.nl http://www.academischecollecties.nl/

**Comment by ndkv** [comment]
Tekst staat nu op juiste plek.
